ignite.instance.name=ignite-server-a

ignite.local.host=10.10.1.11
ignite.discovery.addresses=10.10.1.11:47500..47520,10.10.1.12:47500..47520

ignite.persistence.enabled=true
ignite.persistence.storage.path=ignite/data/storage
ignite.persistence.wal.path=ignite/data/wal
ignite.persistence.wal.archive.path=ignite/data/wal-archive

# ssl конфигурация
ignite.ssl.enabled=true

ignite.ssl.keyStorePath=/opt/ignite/ssl/server.jks
ignite.ssl.keyStorePassword=changeit

ignite.ssl.trustStorePath=/opt/ignite/ssl/trust.jks
ignite.ssl.trustStorePassword=changeit
