ignite.instance.name=ignite-server-a

ignite.local.host=10.10.1.11
ignite.discovery.addresses=10.10.1.11:47500..47520,10.10.1.12:47500..47520

ignite.persistence.enabled=true
ignite.persistence.storage.path=ignite/data/storage
ignite.persistence.wal.path=ignite/data/wal
ignite.persistence.wal.archive.path=ignite/data/wal-archive